name: Build and Push Docker Image

on:
  push:
    paths:
      - 'Backend/**'
      - 'UI/**'


jobs:
  UI:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.paths, 'UI/')

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./UI
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/my-reactapp:latest
        dockerfile: Dockerfile
  Backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.paths, 'Backend/')


    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Backend
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/my-springboot:latest
        dockerfile: Dockerfile      
  deploy:
    name: deploy to AWS EC2
    runs-on: ubuntu-latest
    needs:
       - UI     
    steps:
      - name: checking into repo
        uses: actions/checkout@v2
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
          ssh-add /home/runner/.ssh/github_actions
      - name: Build and deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GITHUB_PACKAGE_URL: ghcr.io
          DOCKER_IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/my-reactapp:latest
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.KNOWN_HOSTS }} -i ~/.ssh/github_actions "docker login ${{ env.GITHUB_PACKAGE_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.GHCR_PAT }}"
          ssh ${{ secrets.USERNAME }}@${{ secrets.KNOWN_HOSTS }} -i ~/.ssh/github_actions "docker pull $DOCKER_IMAGE_TAG"
          ssh ${{ secrets.USERNAME }}@${{ secrets.KNOWN_HOSTS }} -i ~/.ssh/github_actions "docker run -d --name my-reactapp -p 80:80 $DOCKER_IMAGE_TAG"



          