name: Build and Push Docker Image

on:
  push:
    branches:
      - devops

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/my-reactapp:latest
        dockerfile: Dockerfile
   - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USERNAME: ubuntu
        EC2_PUBLIC_IP: 52.87.203.121
        DOCKER_IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/my-reactapp:latest
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $EC2_PUBLIC_IP >> ~/.ssh/known_hosts
        scp -i ~/.ssh/id_rsa -r docker-compose.yml $DOCKER_IMAGE_TAG YOUR_EC2_USERNAME@$EC2_PUBLIC_IP:/home/YOUR_EC2_USERNAME/
        ssh -i ~/.ssh/id_rsa YOUR_EC2_USERNAME@$EC2_PUBLIC_IP 'docker pull $DOCKER_IMAGE_TAG'
        ssh -i ~/.ssh/id_rsa YOUR_EC2_USERNAME@$EC2_PUBLIC_IP 'docker run -d --name my-reactapp -p 80:80 $DOCKER_IMAGE_TAG'
